from datetime import datetime, timezone
import logging
from pathlib import Path
from zoneinfo import ZoneInfo

import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel

from inference.predict_user_aqi import (
    STATION_FORECAST_FILE,
    predict_user_aqi,
)


INDIA_TIMEZONE = ZoneInfo("Asia/Kolkata")

MAX_SERVICE_DISTANCE_KM = 25.0
MAX_CACHE_AGE_HOURS = 2.0
MAX_SOURCE_DATA_AGE_HOURS = 6.0


logging.basicConfig(
    level=logging.INFO,
    format=(
        "%(asctime)s | %(levelname)s | "
        "%(name)s | %(message)s"
    ),
)

logger = logging.getLogger("cleartrace.api")


app = FastAPI(
    title="ClearTrace Forecast API",
    description=(
        "Coordinate-based AQI forecasts generated by blending "
        "the three nearest monitoring stations."
    ),
    version="1.0.0",
)


class RequestedLocation(BaseModel):
    latitude: float
    longitude: float


class NearestStationResponse(BaseModel):
    location_id: str
    station_name: str
    distance_km: float
    blend_weight: float


class ForecastPointResponse(BaseModel):
    timestamp: datetime
    horizon_hours: int
    predicted_aqi: float
    category: str


class ForecastResponse(BaseModel):
    requested_location: RequestedLocation
    generated_at: datetime
    forecast_origin: datetime
    cache_updated_at: datetime
    is_stale: bool
    requested_forecast_hours: int
    available_forecast_hours: int
    nearest_stations: list[NearestStationResponse]
    forecast: list[ForecastPointResponse]


class HealthResponse(BaseModel):
    status: str
    forecast_cache_exists: bool
    cache_updated_at: datetime | None
    cache_age_hours: float | None


def get_aqi_category(aqi: float) -> str:
    """Return the CPCB AQI category."""

    if aqi <= 50:
        return "Good"

    if aqi <= 100:
        return "Satisfactory"

    if aqi <= 200:
        return "Moderate"

    if aqi <= 300:
        return "Poor"

    if aqi <= 400:
        return "Very Poor"

    return "Severe"


def convert_to_india_datetime(value) -> datetime:
    """
    Convert a timestamp to a timezone-aware Asia/Kolkata datetime.
    """

    timestamp = pd.Timestamp(value)

    if timestamp.tzinfo is None:
        timestamp = timestamp.tz_localize(
            INDIA_TIMEZONE
        )
    else:
        timestamp = timestamp.tz_convert(
            INDIA_TIMEZONE
        )

    return timestamp.to_pydatetime()


def get_cache_information():
    if not STATION_FORECAST_FILE.exists():
        raise FileNotFoundError(
            f"Forecast cache does not exist: "
            f"{STATION_FORECAST_FILE}"
        )

    cache_updated_at = datetime.fromtimestamp(
        STATION_FORECAST_FILE.stat().st_mtime,
        tz=timezone.utc,
    ).astimezone(INDIA_TIMEZONE)

    current_time = datetime.now(INDIA_TIMEZONE)

    cache_age_hours = (
        current_time - cache_updated_at
    ).total_seconds() / 3600

    return cache_updated_at, cache_age_hours


@app.get("/")
def root():
    return {
        "service": "ClearTrace Forecast API",
        "status": "running",
        "documentation": "/docs",
    }


@app.get(
    "/health",
    response_model=HealthResponse,
)
def health_check():
    if not STATION_FORECAST_FILE.exists():
        return HealthResponse(
            status="unavailable",
            forecast_cache_exists=False,
            cache_updated_at=None,
            cache_age_hours=None,
        )

    cache_updated_at, cache_age_hours = (
        get_cache_information()
    )

    status = (
        "healthy"
        if cache_age_hours <= MAX_CACHE_AGE_HOURS
        else "stale"
    )

    return HealthResponse(
        status=status,
        forecast_cache_exists=True,
        cache_updated_at=cache_updated_at,
        cache_age_hours=round(
            cache_age_hours,
            2,
        ),
    )


@app.get(
    "/forecast",
    response_model=ForecastResponse,
)
def get_forecast(
    latitude: float = Query(
        ...,
        ge=-90,
        le=90,
        description="User latitude",
    ),
    longitude: float = Query(
        ...,
        ge=-180,
        le=180,
        description="User longitude",
    ),
):
    logger.info(
        "Forecast requested for latitude=%s, longitude=%s",
        latitude,
        longitude,
    )

    try:
        cache_updated_at, cache_age_hours = (
            get_cache_information()
        )

        nearest_stations, user_forecast = (
            predict_user_aqi(
                user_latitude=latitude,
                user_longitude=longitude,
            )
        )

        closest_distance = float(
            nearest_stations["distance_km"].min()
        )

        if closest_distance > MAX_SERVICE_DISTANCE_KM:
            raise HTTPException(
                status_code=422,
                detail=(
                    "This location is outside ClearTrace's "
                    "Delhi monitoring coverage. "
                    f"The closest station is "
                    f"{closest_distance:.2f} km away."
                ),
            )

        current_time = datetime.now(
            INDIA_TIMEZONE
        )

        current_timestamp = pd.Timestamp(
            current_time
        )

        # Never return forecast timestamps that have
        # already passed.
        future_forecast = user_forecast[
            user_forecast["forecast_timestamp"]
            > current_timestamp
        ].copy()

        future_forecast = (
            future_forecast
            .sort_values("forecast_timestamp")
            .head(24)
            .reset_index(drop=True)
        )

        if future_forecast.empty:
            raise HTTPException(
                status_code=503,
                detail=(
                    "The cached forecasts have expired. "
                    "Run the hourly update pipeline."
                ),
            )

        forecast_origin = convert_to_india_datetime(
            user_forecast["forecast_origin"].iloc[0]
        )

        source_data_age_hours = (
            current_time - forecast_origin
        ).total_seconds() / 3600

        is_stale = (
            cache_age_hours > MAX_CACHE_AGE_HOURS
            or source_data_age_hours
            > MAX_SOURCE_DATA_AGE_HOURS
        )

        station_response = []

        for row in nearest_stations.itertuples():
            station_response.append(
                NearestStationResponse(
                    location_id=str(row.location_id),
                    station_name=str(row.station_name),
                    distance_km=round(
                        float(row.distance_km),
                        3,
                    ),
                    blend_weight=round(
                        float(row.blend_weight),
                        4,
                    ),
                )
            )

        forecast_response = []

        for row in future_forecast.itertuples():
            predicted_aqi = float(
                row.predicted_aqi
            )

            forecast_response.append(
                ForecastPointResponse(
                    timestamp=(
                        convert_to_india_datetime(
                            row.forecast_timestamp
                        )
                    ),
                    horizon_hours=int(
                        row.horizon_hours
                    ),
                    predicted_aqi=round(
                        predicted_aqi,
                        2,
                    ),
                    category=get_aqi_category(
                        predicted_aqi
                    ),
                )
            )

        logger.info(
            "Forecast completed: stations=%s, future_hours=%s, "
            "is_stale=%s",
            len(station_response),
            len(forecast_response),
            is_stale,
        )

        return ForecastResponse(
            requested_location=RequestedLocation(
                latitude=latitude,
                longitude=longitude,
            ),
            generated_at=current_time,
            forecast_origin=forecast_origin,
            cache_updated_at=cache_updated_at,
            is_stale=is_stale,
            requested_forecast_hours=24,
            available_forecast_hours=len(
                forecast_response
            ),
            nearest_stations=station_response,
            forecast=forecast_response,
        )

    except HTTPException:
        raise

    except FileNotFoundError as error:
        logger.exception(
            "Forecast cache is unavailable."
        )

        raise HTTPException(
            status_code=503,
            detail=(
                "Forecast data is unavailable. "
                "Run the hourly update pipeline."
            ),
        ) from error

    except ValueError as error:
        logger.exception(
            "Forecast data failed validation."
        )

        raise HTTPException(
            status_code=503,
            detail=(
                "Forecast data failed validation. "
                "Check the hourly pipeline and API logs."
            ),
        ) from error

    except Exception as error:
        logger.exception(
            "Unexpected forecast API failure."
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "Unexpected forecast error. "
                "Check the API server logs."
            ),
        ) from error